apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-deployment
spec:
  selector:
    matchLabels:
      app: open-deployment
  template:
    metadata:
      labels:
        app: open-deployment
    spec:
      containers:
      - name: open-deployment-nginx
        image: nginx:1.21.6
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - name: cm
          mountPath: /var/www/index/html/
      volumes:
      - name: cm
        configMap:
          name: open-configmap
